// Centralized daemon route table — the single place URLs live in the
// frontend. Every fetch in the codebase resolves its path through here so a
// daemon endpoint rename is one edit, not a hunt.
//
// Mirrors contracts/src/http.ts ROUTES. Kept duplicated rather than imported
// because Vite/esbuild doesn't ergonomically pull from ../../../contracts
// without workspace config; the cost of one shadow constants file is small
// compared to the cost of misaligned URLs.

export const ROUTES = {
  health: "/health",
  stream: "/stream",
  workers: "/workers",
  worker: (id) => `/workers/${id}`,
  workerEvents: (id) => `/workers/${id}/events`,
  workerMessage: (id) => `/workers/${id}/message`,
  workerAction: (id) => `/workers/${id}/action`,
  workerPush: (id) => `/workers/${id}/push`,
  workerPushState: (id) => `/workers/${id}/push-state`,
  orchestrators: "/orchestrators",
  orchestratorMessage: (id) => `/orchestrators/${id}/message`,
  policyDecide: "/policy/decide",
  pending: "/pending",
  pendingDecision: (id) => `/pending/${id}/decision`,
  session: "/session",
  metrics: "/metrics",
  uiConfig: "/api/ui-config",
  pickDirectory: "/pick-directory",
  pickFile: "/pick-file",
  fsImage: "/fs/image",
  fsDefaultApp: "/fs/default-app",
  fsOpen: "/fs/open",
  fsIcon: "/fs/icon",
  fsBranches: "/fs/branches",
  fsUnpushed: "/fs/unpushed",
  fsCommit: "/fs/commit",
  fsCheckout: "/fs/checkout",
  fsRecents: "/fs/recents",
  fsRead: "/fs/read",
  fsWrite: "/fs/write",
  fsPaste: "/fs/paste",
  fsReveal: "/fs/reveal",
  workerName: (id) => `/workers/${id}/name`,
  workerPermission: (id) => `/workers/${id}/permission`,
  workerModel: (id) => `/workers/${id}/model`,
  workerDiff: (id) => `/workers/${id}/diff`,
  workerChanges: (id) => `/workers/${id}/changes`,
  workerFileDiff: (id) => `/workers/${id}/changes/file`,
  workerInterrupt: (id) => `/workers/${id}/interrupt`,
  workerKeystroke: (id) => `/workers/${id}/keystroke`,
  workerQuestionAnswer: (id) => `/workers/${id}/question-answer`,
  workerRewindTargets: (id) => `/workers/${id}/rewind-targets`,
  workerRewind: (id) => `/workers/${id}/rewind`,
  workerTryState: (id) => `/workers/${id}/try/state`,
  workerTry: (id) => `/workers/${id}/try`,
  workerTryKeep: (id) => `/workers/${id}/try/keep`,
  workerTryDiscard: (id) => `/workers/${id}/try/discard`,
  commands: "/commands",
  templates: "/api/templates",
  template: (name) => `/api/templates/${name}`,
  settings: "/api/settings",
  fsList: "/fs/list",
  policyRule: "/api/policy/rule",
};
