// Centralized daemon route table — the single place URLs live in the
// frontend. Every fetch in the codebase resolves its path through here so a
// daemon endpoint rename is one edit, not a hunt.
//
// Mirrors contracts/src/http.ts ROUTES. Kept duplicated rather than imported
// because Vite/esbuild doesn't ergonomically pull from ../../../contracts
// without workspace config; the cost of one shadow constants file is small
// compared to the cost of misaligned URLs.

export const ROUTES = {
  health: "/health",
  stream: "/stream",
  workers: "/workers",
  worker: (id) => `/workers/${id}`,
  workerEvents: (id) => `/workers/${id}/events`,
  workerMessage: (id) => `/workers/${id}/message`,
  workerQueue: (id) => `/workers/${id}/queue`,
  workerQueueItem: (id, queueId) => `/workers/${id}/queue/${queueId}`,
  workerAction: (id) => `/workers/${id}/action`,
  workerPush: (id) => `/workers/${id}/push`,
  workerPushState: (id) => `/workers/${id}/push-state`,
  workerPull: (id) => `/workers/${id}/pull`,
  orchestrators: "/orchestrators",
  orchestratorMessage: (id) => `/orchestrators/${id}/message`,
  policyDecide: "/policy/decide",
  pending: "/pending",
  pendingDecision: (id) => `/pending/${id}/decision`,
  metrics: "/metrics",
  uiConfig: "/api/ui-config",
  pickDirectory: "/pick-directory",
  pickFile: "/pick-file",
  fsImage: "/fs/image",
  // On the raw-content listener (daemon.rawPort), not the main API port:
  fsRaw: "/fs/raw",
  pdfjs: "/pdfjs",
  fsDefaultApp: "/fs/default-app",
  fsOpen: "/fs/open",
  fsIcon: "/fs/icon",
  fsBranches: "/fs/branches",
  fsUnpushed: "/fs/unpushed",
  fsCommit: "/fs/commit",
  fsCheckout: "/fs/checkout",
  fsBranchCreate: "/fs/branch/create",
  fsBranchRename: "/fs/branch/rename",
  fsBranchDelete: "/fs/branch/delete",
  fsFetch: "/fs/fetch",
  fsRemoteBranchDelete: "/fs/remote-branch/delete",
  fsRecents: "/fs/recents",
  fsRead: "/fs/read",
  fsWrite: "/fs/write",
  fsPaste: "/fs/paste",
  fsReveal: "/fs/reveal",
  fsStat: "/fs/stat",
  fsCreate: "/fs/create",
  fsRename: "/fs/rename",
  fsMove: "/fs/move",
  fsTrash: "/fs/trash",
  fsWatch: "/fs/watch",
  fsUnwatch: "/fs/unwatch",
  workerName: (id) => `/workers/${id}/name`,
  workerOpen: (id) => `/workers/${id}/open`,
  workerPermission: (id) => `/workers/${id}/permission`,
  workerModel: (id) => `/workers/${id}/model`,
  workerDiff: (id) => `/workers/${id}/diff`,
  workerChanges: (id) => `/workers/${id}/changes`,
  workerFileDiff: (id) => `/workers/${id}/changes/file`,
  workerConflicts: (id) => `/workers/${id}/conflicts`,
  workerConflictFile: (id) => `/workers/${id}/conflicts/file`,
  workerConflictResolve: (id) => `/workers/${id}/conflicts/resolve`,
  workerMemory: (id) => `/workers/${id}/memory`,
  workerMemoryItem: (id, name) => `/workers/${id}/memory/${name}`,
  workerInterrupt: (id) => `/workers/${id}/interrupt`,
  workerKeystroke: (id) => `/workers/${id}/keystroke`,
  workerQuestionAnswer: (id) => `/workers/${id}/question-answer`,
  workerRewindTargets: (id) => `/workers/${id}/rewind-targets`,
  workerRewind: (id) => `/workers/${id}/rewind`,
  workerTerminal: (id) => `/workers/${id}/terminal`,
  terminal: "/terminal",
  terminalKill: (runId) => `/terminal/${runId}/kill`,
  workerTryState: (id) => `/workers/${id}/try/state`,
  workerTry: (id) => `/workers/${id}/try`,
  workerTryKeep: (id) => `/workers/${id}/try/keep`,
  workerTryDiscard: (id) => `/workers/${id}/try/discard`,
  commands: "/commands",
  templates: "/api/templates",
  template: (name) => `/api/templates/${name}`,
  settings: "/api/settings",
  updateStatus: "/api/updates/status",
  updateCheck: "/api/updates/check",
  updateApply: "/api/updates/apply",
  updateDefer: "/api/updates/defer",
  fsList: "/fs/list",
  policyRule: "/api/policy/rule",
};
